# Generated by Django 4.0.2 on 2022-03-09 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('ownername', models.CharField(max_length=99, unique=True)),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(blank=True, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999999'", regex='^[7-9]{1}\\d{9}')])),
            ],
            options={
                'db_table': 'Owner',
            },
        ),
    ]
