# Generated by Django 3.2.5 on 2022-03-11 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_ownerregistration_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerregistration',
            name='password',
        ),
    ]
