# Generated by Django 4.0.2 on 2022-03-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_remove_ownerregistration_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerregistration',
            name='password',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
