# Generated by Django 4.0.2 on 2022-03-24 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finderregistration1',
            old_name='phone_number',
            new_name='phone_numbers',
        ),
    ]
