# Generated by Django 4.0.2 on 2022-03-24 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_rename_phone_number_finderregistration1_phone_numbers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finderregistration1',
            old_name='phone_numbers',
            new_name='phone_number',
        ),
    ]
