# Generated by Django 4.0.2 on 2022-03-24 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_rename_phone_numbers_finderregistration1_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finderregistration1',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='ownerregistration1',
            name='phone_number',
        ),
    ]
