# Generated by Django 4.0.2 on 2022-03-24 05:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_remove_finderregistration1_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finderregistration1',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999999'", regex='^[7-9]{1}\\d{9}')]),
        ),
        migrations.AddField(
            model_name='ownerregistration1',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999999'", regex='^[7-9]{1}\\d{9}')]),
        ),
    ]
